### ISSUE TITLE
TimestampStart

### ISSUE THREAD

**Issue by aviweit** [5GZORRO/mda#10]
Hi Andre,

I noticed that timestampStart and timestampEnd are marked as optional configurations.

When attempting not to send them as part of the monitoring spec, I encountered the below error. I am using v1.2.1

`"status":"Error","message":"Timestamp start need to be after current now."`

In my opinion, I think it would be good to automatically start metric collection in case timestampStart is not being provided, or in case it holds a value that is prior to `now`. I think in case timestampEnd is not being provided then it can endlessly collect the metrics until NS is probably terminated.

Thanks.

**Comment by andreggouveia** [comment]
Yes, it was also our intention to grant the capability, when field timestampStart is not being provided, to automatically start the metric collection. Also, when the monitoring spec does not provide the timestampEnd, it is possible to explicit stop/disable the config with a PUT endpoint (...settings/:id/disable).
