### ISSUE TITLE
mda terminates with: sqlalchemy ImportError

### ISSUE THREAD

**Issue by aviweit** [5GZORRO/mda#4]
When trying to build mda from sources:

```
docker-compose -f docker-compose-development.yml  up --build
```

mda terminates with: `ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query'`

Modifying Dockerfile to install the previous version of sqlalchemy i.e. `sqlalchemy==1.3.23` fixed this issue for me.

**Comment by andreggouveia** [comment]
If I'm not mistaken, this error is solved if, instead of docker-compose-development, docker-compose-production file is used (because of the packages).  
Nevertheless, thank you for solving and addressing that error. We will modify our Dockerfile accordingly with your comment.
