### ISSUE TITLE
businessID should be of a type string (uuid)

### ISSUE THREAD

**Issue by aviweit** [5GZORRO/mda#5]
When I pass MDA a setting that contains businessID as a uuid string,  I get

```
{"detail":[{"loc":["body","businessID"],"msg":"value is not a valid integer","type":"type_error.integer"}]}
```

To my understanding, businessID is the transaction_uuid of the ISSM flow which is in a uuid format as indicated by the examples below:

`6cc52f2c24ff4e4c901d49ee701b8223`, `c907cedc-5fd3-47a9-9188-6e6bc401d870`

Thanks.

**Comment by andreggouveia** [comment]
Yes, you are completely right, this error had been previously detected, and will be corrected asap when we update the current version of the MDA. Thank you @aviweit!
