### ISSUE TITLE
Remove hard coded kafka topic

### ISSUE THREAD

**Issue by aviweit** [5GZORRO/mda#8]
I can see that kafka topic is hard coded as `topic_test`: https://github.com/5GZORRO/mda/blob/main/mda/app/main.py#L147.

I think it should be retrieved from the metadata section of the monitoring spec.

**Comment by andreggouveia** [comment]
Fixed issue. The Kafka topic where we send the raw and encrypted data is now configurable on the monitoring spec.

**Comment by aviweit** [comment]
I can see that it is hard coded to `topic_test`.

Thanks.

**Comment by andreggouveia** [comment]
You're right, onwards it is no longer hard coded. 

Thanks for the valuable feedback Avi.
